# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'img1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(584, 535)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 78, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 65, 65))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 78, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 65, 65))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 78, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 65, 65))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 26, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(70, 70, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.image2 = QtWidgets.QLabel(self.layoutWidget)
        self.image2.setMaximumSize(QtCore.QSize(96, 26))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.image2.setFont(font)
        self.image2.setObjectName("image2")
        self.verticalLayout_3.addWidget(self.image2)
        self.org_img2 = QtWidgets.QLabel(self.layoutWidget)
        self.org_img2.setFrameShape(QtWidgets.QFrame.Box)
        self.org_img2.setText("")
        self.org_img2.setScaledContents(True)
        self.org_img2.setObjectName("org_img2")
        self.verticalLayout_3.addWidget(self.org_img2)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.option2 = QtWidgets.QComboBox(self.layoutWidget)
        self.option2.setMaximumSize(QtCore.QSize(96, 26))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.option2.setFont(font)
        self.option2.setObjectName("option2")
        self.option2.addItem("")
        self.option2.addItem("")
        self.option2.addItem("")
        self.option2.addItem("")
        self.option2.addItem("")
        self.verticalLayout_4.addWidget(self.option2)
        self.comp_img2 = QtWidgets.QLabel(self.layoutWidget)
        self.comp_img2.setFrameShape(QtWidgets.QFrame.Box)
        self.comp_img2.setText("")
        self.comp_img2.setScaledContents(True)
        self.comp_img2.setObjectName("comp_img2")
        self.verticalLayout_4.addWidget(self.comp_img2)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.image1 = QtWidgets.QLabel(self.layoutWidget)
        self.image1.setMaximumSize(QtCore.QSize(96, 26))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.image1.setFont(font)
        self.image1.setObjectName("image1")
        self.verticalLayout.addWidget(self.image1)
        self.org_img1 = QtWidgets.QLabel(self.layoutWidget)
        self.org_img1.setFrameShape(QtWidgets.QFrame.Box)
        self.org_img1.setText("")
        self.org_img1.setScaledContents(True)
        self.org_img1.setObjectName("org_img1")
        self.verticalLayout.addWidget(self.org_img1)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.option1 = QtWidgets.QComboBox(self.layoutWidget)
        self.option1.setMaximumSize(QtCore.QSize(96, 26))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.option1.setFont(font)
        self.option1.setObjectName("option1")
        self.option1.addItem("")
        self.option1.addItem("")
        self.option1.addItem("")
        self.option1.addItem("")
        self.option1.addItem("")
        self.verticalLayout_2.addWidget(self.option1)
        self.comp_img1 = QtWidgets.QLabel(self.layoutWidget)
        self.comp_img1.setFrameShape(QtWidgets.QFrame.Box)
        self.comp_img1.setText("")
        self.comp_img1.setScaledContents(True)
        self.comp_img1.setObjectName("comp_img1")
        self.verticalLayout_2.addWidget(self.comp_img1)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.output1 = QtWidgets.QLabel(self.layoutWidget1)
        self.output1.setMaximumSize(QtCore.QSize(95, 26))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.output1.setFont(font)
        self.output1.setObjectName("output1")
        self.verticalLayout_6.addWidget(self.output1)
        self.img_out1 = QtWidgets.QLabel(self.layoutWidget1)
        self.img_out1.setFrameShape(QtWidgets.QFrame.Box)
        self.img_out1.setText("")
        self.img_out1.setScaledContents(True)
        self.img_out1.setObjectName("img_out1")
        self.verticalLayout_6.addWidget(self.img_out1)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.output2 = QtWidgets.QLabel(self.layoutWidget1)
        self.output2.setMaximumSize(QtCore.QSize(96, 26))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.output2.setFont(font)
        self.output2.setObjectName("output2")
        self.verticalLayout_7.addWidget(self.output2)
        self.img_out2 = QtWidgets.QLabel(self.layoutWidget1)
        self.img_out2.setFrameShape(QtWidgets.QFrame.Box)
        self.img_out2.setText("")
        self.img_out2.setScaledContents(True)
        self.img_out2.setObjectName("img_out2")
        self.verticalLayout_7.addWidget(self.img_out2)
        self.gridLayout_3.addLayout(self.verticalLayout_7, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.comp1 = QtWidgets.QLabel(self.layoutWidget1)
        self.comp1.setMaximumSize(QtCore.QSize(161, 18))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.comp1.setFont(font)
        self.comp1.setObjectName("comp1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.comp1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.imagechosen1 = QtWidgets.QComboBox(self.layoutWidget1)
        self.imagechosen1.setMaximumSize(QtCore.QSize(92, 26))
        self.imagechosen1.setObjectName("imagechosen1")
        self.imagechosen1.addItem("")
        self.imagechosen1.addItem("")
        self.imagechosen1.addItem("")
        self.horizontalLayout_2.addWidget(self.imagechosen1)
        self.ratio2_2 = QtWidgets.QSlider(self.layoutWidget1)
        self.ratio2_2.setOrientation(QtCore.Qt.Horizontal)
        self.ratio2_2.setObjectName("ratio2")
        self.horizontalLayout_2.addWidget(self.ratio2_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.compchosen1 = QtWidgets.QComboBox(self.layoutWidget1)
        self.compchosen1.setObjectName("compchosen1")
        self.compchosen1.addItem("")
        self.compchosen1.addItem("")
        self.compchosen1.addItem("")
        self.compchosen1.addItem("")
        self.compchosen1.addItem("")
        self.compchosen1.addItem("")
        self.compchosen1.addItem("")
        self.verticalLayout_5.addWidget(self.compchosen1)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_5)
        self.gridLayout_5.addLayout(self.formLayout, 1, 0, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSpacing(6)
        self.formLayout_2.setObjectName("formLayout_2")
        self.comp2 = QtWidgets.QLabel(self.layoutWidget1)
        self.comp2.setMaximumSize(QtCore.QSize(161, 18))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.comp2.setFont(font)
        self.comp2.setObjectName("comp2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.comp2)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.imagechosen2 = QtWidgets.QComboBox(self.layoutWidget1)
        self.imagechosen2.setMaximumSize(QtCore.QSize(92, 26))
        self.imagechosen2.setObjectName("imagechosen2")
        self.imagechosen2.addItem("")
        self.imagechosen2.addItem("")
        self.imagechosen2.addItem("")
        self.horizontalLayout_3.addWidget(self.imagechosen2)
        self.ratio2 = QtWidgets.QSlider(self.layoutWidget1)
        self.ratio2.setOrientation(QtCore.Qt.Horizontal)
        self.ratio2.setObjectName("ratio1")
        self.horizontalLayout_3.addWidget(self.ratio2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.compchosen2 = QtWidgets.QComboBox(self.layoutWidget1)
        self.compchosen2.setObjectName("compchosen2")
        self.compchosen2.addItem("")
        self.compchosen2.addItem("")
        self.compchosen2.addItem("")
        self.compchosen2.addItem("")
        self.compchosen2.addItem("")
        self.compchosen2.addItem("")
        self.compchosen2.addItem("")
        self.verticalLayout_8.addWidget(self.compchosen2)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_8)
        self.gridLayout_5.addLayout(self.formLayout_2, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mixing = QtWidgets.QLabel(self.layoutWidget1)
        self.mixing.setMaximumSize(QtCore.QSize(201, 18))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.mixing.setFont(font)
        self.mixing.setObjectName("mixing")
        self.horizontalLayout.addWidget(self.mixing)
        self.outputoptions = QtWidgets.QComboBox(self.layoutWidget1)
        self.outputoptions.setObjectName("outputoptions")
        self.outputoptions.addItem("")
        self.outputoptions.addItem("")
        self.outputoptions.addItem("")
        self.horizontalLayout.addWidget(self.outputoptions)
        self.gridLayout_5.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 584, 20))
        self.menuBar.setObjectName("menuBar")
        self.menuFIle = QtWidgets.QMenu(self.menuBar)
        self.menuFIle.setObjectName("menuFIle")
        self.menuOpen = QtWidgets.QMenu(self.menuFIle)
        self.menuOpen.setObjectName("menuOpen")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionimg1 = QtWidgets.QAction(MainWindow)
        self.actionimg1.setObjectName("actionimg1")
        self.actionimg2 = QtWidgets.QAction(MainWindow)
        self.actionimg2.setObjectName("actionimg2")
        self.menuOpen.addSeparator()
        self.menuOpen.addAction(self.actionimg1)
        self.menuOpen.addAction(self.actionimg2)
        self.menuFIle.addSeparator()
        self.menuFIle.addSeparator()
        self.menuFIle.addAction(self.menuOpen.menuAction())
        self.menuFIle.addSeparator()
        self.menuFIle.addAction(self.actionExit)
        self.menuBar.addAction(self.menuFIle.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.image2.setText(_translate("MainWindow", "Image 2"))
        self.option2.setItemText(0, _translate("MainWindow", "Options"))
        self.option2.setItemText(1, _translate("MainWindow", "FT_Mag"))
        self.option2.setItemText(2, _translate("MainWindow", "FT_Phase"))
        self.option2.setItemText(3, _translate("MainWindow", "FT_Real"))
        self.option2.setItemText(4, _translate("MainWindow", "FT_Imag"))
        self.image1.setText(_translate("MainWindow", "Image 1"))
        self.option1.setItemText(0, _translate("MainWindow", "Options"))
        self.option1.setItemText(1, _translate("MainWindow", "FT_Mag"))
        self.option1.setItemText(2, _translate("MainWindow", "FT_Phase"))
        self.option1.setItemText(3, _translate("MainWindow", "FT_Real"))
        self.option1.setItemText(4, _translate("MainWindow", "FT_Imag"))
        self.output1.setText(_translate("MainWindow", "Output1"))
        self.output2.setText(_translate("MainWindow", "Output2"))
        self.comp1.setText(_translate("MainWindow", "Component 1:"))
        self.imagechosen1.setItemText(0, _translate("MainWindow", "Options"))
        self.imagechosen1.setItemText(1, _translate("MainWindow", "Img_1"))
        self.imagechosen1.setItemText(2, _translate("MainWindow", "Img_2"))
        self.compchosen1.setItemText(0, _translate("MainWindow", "Options"))
        self.compchosen1.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.compchosen1.setItemText(2, _translate("MainWindow", "Phase"))
        self.compchosen1.setItemText(3, _translate("MainWindow", "Real"))
        self.compchosen1.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.compchosen1.setItemText(5, _translate("MainWindow", "uniform magnitude"))
        self.compchosen1.setItemText(6, _translate("MainWindow", "uniform phase"))
        self.comp2.setText(_translate("MainWindow", "Component 2:"))
        self.imagechosen2.setItemText(0, _translate("MainWindow", "Options"))
        self.imagechosen2.setItemText(1, _translate("MainWindow", "Img_1"))
        self.imagechosen2.setItemText(2, _translate("MainWindow", "Img_2"))
        self.compchosen2.setItemText(0, _translate("MainWindow", "Options"))
        self.compchosen2.setItemText(1, _translate("MainWindow", "Magnitude"))
        self.compchosen2.setItemText(2, _translate("MainWindow", "Phase"))
        self.compchosen2.setItemText(3, _translate("MainWindow", "Real"))
        self.compchosen2.setItemText(4, _translate("MainWindow", "Imaginary"))
        self.compchosen2.setItemText(5, _translate("MainWindow", "uniform magnitude"))
        self.compchosen2.setItemText(6, _translate("MainWindow", "uniform phase"))
        self.mixing.setText(_translate("MainWindow", "Mixer Output To :"))
        self.outputoptions.setItemText(0, _translate("MainWindow", "Options"))
        self.outputoptions.setItemText(1, _translate("MainWindow", "Output_2"))
        self.outputoptions.setItemText(2, _translate("MainWindow", "Output_1"))
        self.menuFIle.setTitle(_translate("MainWindow", "FIle"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionimg1.setText(_translate("MainWindow", "img1"))
        self.actionimg2.setText(_translate("MainWindow", "img2"))

